const KEY='mestizo-v1';
const seed={pinHash:null,suppliers:[
 {id:'s1',name:'Ejemplo · Bebidas Costa',phone:'34600000001',products:[{id:'p1',name:'Agua 1,5 L',unit:'caja de 12'},{id:'p2',name:'Cerveza rubia',unit:'caja de 24'},{id:'p3',name:'Refresco cola',unit:'caja de 24'}]},
 {id:'s2',name:'Ejemplo · Frescos del Mar',phone:'34600000002',products:[{id:'p4',name:'Limón',unit:'caja'},{id:'p5',name:'Aguacate',unit:'caja'},{id:'p6',name:'Tomate',unit:'caja de 6 kg'}]},
 {id:'s3',name:'Ejemplo · Bodega Arena',phone:'34600000003',products:[{id:'p7',name:'Vino blanco',unit:'caja de 6'},{id:'p8',name:'Cava brut',unit:'caja de 6'}]}
],quantities:{},history:[],unlocked:false};
let state=load(),view='order',openSupplier=state.suppliers[0]?.id,modal=null;
function load(){try{return {...structuredClone(seed),...JSON.parse(localStorage.getItem(KEY)||'{}'),unlocked:false}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify({...state,unlocked:false}))}
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function selectedCount(s){return s.products.reduce((n,p)=>n+(state.quantities[p.id]>0?1:0),0)}
function selectedSuppliers(){return state.suppliers.map(s=>({...s,products:s.products.filter(p=>state.quantities[p.id]>0)})).filter(s=>s.products.length)}
function appShell(body){return `<div class="app"><header class="topbar"><div class="brand"><div class="brand-mark">M</div><div><h1>Mestizo</h1><small>Pedidos semanales</small></div></div><button class="icon-btn" data-action="lock" aria-label="Bloquear">⌾</button></header><main class="content">${body}</main>${nav()}</div>${modalHtml()}`}
function nav(){return `<nav class="bottom-nav" aria-label="Navegación"><button class="nav-btn ${view==='order'?'active':''}" data-view="order"><span>＋</span>Pedido</button><button class="nav-btn ${view==='history'?'active':''}" data-view="history"><span>↻</span>Historial</button><button class="nav-btn ${view==='edit'?'active':''}" data-view="edit"><span>⚙</span>Editar</button></nav>`}
function orderView(){const total=selectedSuppliers().length;return `<section class="hero"><p class="eyebrow">Nuevo pedido</p><h2>¿Qué hace falta<br>esta semana?</h2><p>Marca las cajas de cada proveedor.</p></section>${state.suppliers.length?state.suppliers.map(s=>`<article class="supplier-card ${openSupplier===s.id?'open':''}"><button class="supplier-head" data-open="${s.id}"><span class="supplier-avatar">${esc(s.name.charAt(0))}</span><span class="supplier-title"><strong>${esc(s.name)}</strong><span>${s.products.length} productos</span></span>${selectedCount(s)?`<span class="badge">${selectedCount(s)}</span>`:''}<span class="chevron">⌄</span></button>${openSupplier===s.id?`<div class="products">${s.products.map(p=>`<div class="product"><div class="product-info"><strong>${esc(p.name)}</strong><span>${esc(p.unit)}</span></div><div class="stepper"><button data-qty="${p.id}" data-delta="-1" aria-label="Restar ${esc(p.name)}">−</button><span class="qty">${state.quantities[p.id]||0}</span><button data-qty="${p.id}" data-delta="1" aria-label="Sumar ${esc(p.name)}">+</button></div></div>`).join('')}</div>`:''}</article>`).join(''):`<div class="empty"><span class="emoji">🏖️</span>Añade tu primer proveedor desde Editar.</div>`}<div class="cta-bar"><button class="primary" data-action="summary" ${total?'':'disabled'}>Revisar pedido${total?` · ${total} proveedor${total>1?'es':''}`:''}</button></div>`}
function summaryView(){const groups=selectedSuppliers();return `<div class="section-title"><h2>Resumen</h2><button data-view="order">Seguir editando</button></div>${groups.map(s=>`<article class="summary-card"><h3>${esc(s.name)}</h3>${s.products.map(p=>`<div class="summary-row"><span>${esc(p.name)}<small> · ${esc(p.unit)}</small></span><b>${state.quantities[p.id]}</b></div>`).join('')}<div class="summary-actions"><button class="primary" data-send="${s.id}">Abrir WhatsApp</button></div></article>`).join('')}<p class="note">WhatsApp se abrirá con el mensaje preparado. Revisa el texto y pulsa Enviar allí.</p><button class="secondary" data-action="save-order">Guardar pedido en historial</button>`}
function historyView(){return `<div class="section-title"><h2>Historial</h2></div>${state.history.length?state.history.map(h=>`<article class="history-card"><h3>${new Date(h.date).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})}</h3><div class="history-meta">${h.groups.length} proveedor${h.groups.length!==1?'es':''} · ${h.groups.reduce((n,g)=>n+g.items.length,0)} productos</div><div class="history-actions"><button class="secondary" data-repeat="${h.id}">Repetir pedido</button><button class="mini-btn" data-delete-history="${h.id}" aria-label="Eliminar">×</button></div></article>`).join(''):`<div class="empty"><span class="emoji">🧾</span>Aquí aparecerán los pedidos guardados.</div>`}`}
function editView(){return `<div class="section-title"><h2>Proveedores</h2><button data-add-supplier>+ Añadir</button></div><div class="edit-list">${state.suppliers.map((s,i)=>`<article class="edit-item"><button class="mini-btn" data-move-supplier="${s.id}" data-dir="-1" ${i===0?'disabled':''}>↑</button><div class="grow" data-edit-supplier="${s.id}"><strong>${esc(s.name)}</strong><small>${esc(s.phone)} · ${s.products.length} productos</small></div><button class="mini-btn" data-edit-supplier="${s.id}">✎</button></article>`).join('')}</div><p class="note">Mantén los teléfonos con prefijo de país, sin espacios: por ejemplo, 34600111222.</p>`}
function modalHtml(){if(!modal)return'';if(modal.type==='supplier'){const s=state.suppliers.find(x=>x.id===modal.id);return `<div class="overlay" data-close><section class="sheet" onclick="event.stopPropagation()"><h2>${s?'Editar':'Nuevo'} proveedor</h2><form id="supplier-form" class="fields"><div class="field"><label>Nombre</label><input name="name" value="${esc(s?.name||'')}" required placeholder="Distribuciones Sol"></div><div class="field"><label>WhatsApp</label><input name="phone" inputmode="tel" value="${esc(s?.phone||'34')}" required placeholder="34600111222"></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>${s?`<h3>Productos</h3><div class="edit-list">${s.products.map((p,i)=>`<div class="edit-item"><button class="mini-btn" data-move-product="${p.id}" data-supplier="${s.id}" data-dir="-1" ${i===0?'disabled':''}>↑</button><div class="grow"><strong>${esc(p.name)}</strong><small>${esc(p.unit)}</small></div><button class="mini-btn" data-edit-product="${p.id}" data-supplier="${s.id}">✎</button></div>`).join('')}</div><button class="secondary" data-add-product="${s.id}" style="margin-top:12px">+ Añadir producto</button><button class="danger" data-delete-supplier="${s.id}" style="margin-top:28px">Eliminar proveedor</button>`:''}</section></div>`}if(modal.type==='product'){const s=state.suppliers.find(x=>x.id===modal.supplierId),p=s.products.find(x=>x.id===modal.id);return `<div class="overlay" data-close><section class="sheet" onclick="event.stopPropagation()"><h2>${p?'Editar':'Nuevo'} producto</h2><form id="product-form" class="fields"><div class="field"><label>Producto</label><input name="name" value="${esc(p?.name||'')}" required placeholder="Agua 1,5 L"></div><div class="field"><label>Formato</label><input name="unit" value="${esc(p?.unit||'caja')}" required placeholder="caja de 12"></div><div class="form-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>${p?`<button class="danger" data-delete-product="${p.id}" data-supplier="${s.id}" style="margin-top:22px">Eliminar producto</button>`:''}</section></div>`}return''}
function lockView(){const setup=!state.pinHash;return `<main class="lock"><section class="lock-card"><div class="lock-logo">M</div><h1>${setup?'Bienvenido a Mestizo':'Hola de nuevo'}</h1><p>${setup?'Crea un PIN de 4 a 8 cifras para proteger tus pedidos en este dispositivo.':'Introduce tu PIN para continuar.'}</p><form id="pin-form"><div class="field"><input class="pin" name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" autocomplete="${setup?'new-password':'current-password'}" required autofocus></div><div id="pin-error" class="error"></div><button class="primary">${setup?'Crear PIN':'Entrar'}</button></form>${!setup?'<button class="text-btn" data-action="reset" style="margin-top:15px">He olvidado el PIN</button>':''}<p class="note" style="margin-top:20px">Los datos se guardan solo en este dispositivo.</p></section></main>`}
function render(){document.querySelector('#app').innerHTML=!state.unlocked?lockView():appShell(view==='order'?orderView():view==='summary'?summaryView():view==='history'?historyView():editView());bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{view=e.dataset.view;modal=null;render()});document.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>{openSupplier=openSupplier===e.dataset.open?null:e.dataset.open;render()});document.querySelectorAll('[data-qty]').forEach(e=>e.onclick=()=>{const id=e.dataset.qty;state.quantities[id]=Math.max(0,(state.quantities[id]||0)+Number(e.dataset.delta));save();render()});document.querySelector('[data-action="summary"]')?.addEventListener('click',()=>{view='summary';render()});document.querySelector('[data-action="lock"]')?.addEventListener('click',()=>{state.unlocked=false;render()});document.querySelectorAll('[data-close]').forEach(e=>e.onclick=()=>{modal=null;render()});document.querySelector('[data-add-supplier]')?.addEventListener('click',()=>{modal={type:'supplier'};render()});document.querySelectorAll('[data-edit-supplier]').forEach(e=>e.onclick=()=>{modal={type:'supplier',id:e.dataset.editSupplier};render()});document.querySelectorAll('[data-add-product]').forEach(e=>e.onclick=()=>{modal={type:'product',supplierId:e.dataset.addProduct};render()});document.querySelectorAll('[data-edit-product]').forEach(e=>e.onclick=()=>{modal={type:'product',supplierId:e.dataset.supplier,id:e.dataset.editProduct};render()});document.querySelectorAll('[data-send]').forEach(e=>e.onclick=()=>sendWhatsApp(e.dataset.send));document.querySelectorAll('[data-repeat]').forEach(e=>e.onclick=()=>repeatOrder(e.dataset.repeat));document.querySelectorAll('[data-delete-history]').forEach(e=>e.onclick=()=>{if(confirm('¿Eliminar este pedido del historial?')){state.history=state.history.filter(h=>h.id!==e.dataset.deleteHistory);save();render()}});document.querySelector('[data-action="save-order"]')?.addEventListener('click',saveOrder);document.querySelector('[data-action="reset"]')?.addEventListener('click',resetData);document.querySelector('#pin-form')?.addEventListener('submit',pinSubmit);document.querySelector('#supplier-form')?.addEventListener('submit',supplierSubmit);document.querySelector('#product-form')?.addEventListener('submit',productSubmit);document.querySelectorAll('[data-delete-supplier]').forEach(e=>e.onclick=()=>deleteSupplier(e.dataset.deleteSupplier));document.querySelectorAll('[data-delete-product]').forEach(e=>e.onclick=()=>deleteProduct(e.dataset.supplier,e.dataset.deleteProduct));document.querySelectorAll('[data-move-supplier]').forEach(e=>e.onclick=()=>move(state.suppliers,e.dataset.moveSupplier,Number(e.dataset.dir)));document.querySelectorAll('[data-move-product]').forEach(e=>e.onclick=()=>move(state.suppliers.find(s=>s.id===e.dataset.supplier).products,e.dataset.moveProduct,Number(e.dataset.dir)))}
async function pinSubmit(ev){ev.preventDefault();const pin=new FormData(ev.target).get('pin'),h=await hash(pin);if(!state.pinHash){state.pinHash=h;state.unlocked=true;save();render();return}if(h===state.pinHash){state.unlocked=true;render()}else document.querySelector('#pin-error').textContent='El PIN no es correcto.'}
function resetData(){if(confirm('Se borrarán proveedores, pedidos y PIN de este dispositivo. ¿Continuar?')){localStorage.removeItem(KEY);state=structuredClone(seed);render()}}
function supplierSubmit(ev){ev.preventDefault();const d=Object.fromEntries(new FormData(ev.target)),phone=d.phone.replace(/\D/g,'');if(phone.length<8){toast('Revisa el teléfono');return}if(modal.id){Object.assign(state.suppliers.find(s=>s.id===modal.id),{name:d.name.trim(),phone})}else{const s={id:uid(),name:d.name.trim(),phone,products:[]};state.suppliers.push(s);openSupplier=s.id}save();modal=null;render()}
function productSubmit(ev){ev.preventDefault();const d=Object.fromEntries(new FormData(ev.target)),s=state.suppliers.find(x=>x.id===modal.supplierId);if(modal.id)Object.assign(s.products.find(p=>p.id===modal.id),{name:d.name.trim(),unit:d.unit.trim()});else s.products.push({id:uid(),name:d.name.trim(),unit:d.unit.trim()});save();modal={type:'supplier',id:s.id};render()}
function deleteSupplier(id){if(!confirm('¿Eliminar este proveedor y sus productos?'))return;state.suppliers=state.suppliers.filter(s=>s.id!==id);save();modal=null;render()}
function deleteProduct(sid,pid){if(!confirm('¿Eliminar este producto?'))return;const s=state.suppliers.find(x=>x.id===sid);s.products=s.products.filter(p=>p.id!==pid);delete state.quantities[pid];save();modal={type:'supplier',id:sid};render()}
function move(arr,id,dir){const i=arr.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];save();render()}
function groupsSnapshot(){return selectedSuppliers().map(s=>({supplierId:s.id,supplierName:s.name,phone:s.phone,items:s.products.map(p=>({productId:p.id,name:p.name,unit:p.unit,quantity:state.quantities[p.id]}))}))}
function saveOrder(){const groups=groupsSnapshot();state.history.unshift({id:uid(),date:new Date().toISOString(),groups});state.history=state.history.slice(0,50);save();toast('Pedido guardado');view='history';setTimeout(render,300)}
function repeatOrder(id){const h=state.history.find(x=>x.id===id);state.quantities={};h.groups.forEach(g=>g.items.forEach(i=>{if(state.suppliers.some(s=>s.products.some(p=>p.id===i.productId)))state.quantities[i.productId]=i.quantity}));save();view='summary';render();toast('Cantidades cargadas para revisar')}
function sendWhatsApp(id){const s=state.suppliers.find(x=>x.id===id),items=s.products.filter(p=>state.quantities[p.id]>0);const lines=[`Hola ${s.name}, pedido de Mestizo:`,...items.map(p=>`• ${state.quantities[p.id]} × ${p.name} (${p.unit})`),'','Gracias.'];window.open(`https://wa.me/${s.phone}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank','noopener')}
render();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
