(function(root){
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function findInvoiceDates(text){
    const results=new Map(),months=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
    for(const line of text.toLowerCase().split('\n')){
      const candidates=[...line.matchAll(/\b(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{4}|\d{2})\b/g)].map(m=>[+m[1],+m[2],+m[3]]);
      for(const m of line.matchAll(/\b(\d{4})-(\d{2})-(\d{2})\b/g))candidates.push([+m[3],+m[2],+m[1]]);
      for(const m of line.matchAll(/\b(\d{1,2})\s+(?:de\s+)?(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+(?:de\s+)?(\d{4})\b/g))candidates.push([+m[1],months.indexOf(m[2])+1,+m[3]]);
      for(let [day,month,year] of candidates){if(year<100)year+=2000;const date=new Date(Date.UTC(year,month-1,day));if(year<2000||year>2099||date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day)continue;const iso=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,score=/vencimiento|venc\.|entrega|pago/.test(line)?-1:/fecha|emisi[oó]n|expedici[oó]n/.test(line)?2:0;results.set(iso,Math.max(results.get(iso)??-2,score))}
    }
    return [...results].map(([date,score])=>({date,score})).sort((a,b)=>b.score-a.score);
  }
  if(typeof module!=='undefined'&&module.exports){module.exports={findInvoiceDates};return}
  let dbPromise,entries=[],pending=null,busy=false,error='',progress='',month='',detail=null,previewUrl=null,active=()=>false,redraw=()=>{},initialized=false;
  const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('es-ES');
  function db(){return dbPromise ||=new Promise((resolve,reject)=>{const req=indexedDB.open('mestizo-invoices',1);req.onupgradeneeded=()=>req.result.createObjectStore('invoices',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function storage(mode,fn){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('invoices',mode);const req=fn(tx.objectStore('invoices'));tx.oncomplete=()=>resolve(req?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('No se pudo guardar la factura'))})}
  async function refresh(){entries=await storage('readonly',s=>s.getAll());entries.sort((a,b)=>b.date.localeCompare(a.date));if(!month&&entries.length)month=entries[0].date.slice(0,7)}
  function update(){if(active())redraw()}
  function view(){const months=[...new Set(entries.map(e=>e.date.slice(0,7)))].sort().reverse(),filtered=entries.filter(e=>!month||e.date.startsWith(month));return `<div class="section-title"><h2>Facturas</h2></div><p class="note">Fotografía la factura. Leeremos su fecha para archivarla por mes en este móvil.</p><div class="invoice-actions"><label class="primary">Hacer foto<input id="invoice-camera" type="file" accept="image/*" capture="environment" ${busy?'disabled':''}></label><label class="secondary">Elegir foto<input id="invoice-file" type="file" accept="image/*" ${busy?'disabled':''}></label></div>${busy?`<p role="status">${escape(progress)}</p>`:''}${error?`<p class="error" role="alert">${escape(error)}</p>`:''}${pending?`<section class="form-card"><h3>Confirma la fecha de la factura</h3><p class="note">${escape(pending.reason)}</p><form id="invoice-confirm"><div class="field"><label for="invoice-date">Fecha impresa en la factura</label><input id="invoice-date" name="date" type="date" value="${pending.date||''}" required></div><div class="form-actions"><button type="button" class="secondary" id="invoice-cancel">Cancelar</button><button class="primary">Archivar</button></div></form></section>`:''}<p class="note">Las fotos se guardan solo en este navegador. Puedes descargar una copia; borrar los datos del navegador elimina el archivo.</p>${months.length?`<div class="field"><label for="invoice-month">Mes</label><select id="invoice-month">${months.map(m=>`<option value="${m}" ${month===m?'selected':''}>${new Date(m+'-01T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</option>`).join('')}</select></div>`:''}<p class="note">${filtered.length} facturas${month?' en este mes':''}</p>${filtered.length?filtered.map(e=>`<button class="revenue-day" data-invoice="${e.id}"><span><b>Factura · ${dateLabel(e.date)}</b><small>${escape(e.name)}</small></span><span>›</span></button>`).join(''):'<div class="empty">Todavía no hay facturas archivadas.</div>'}${detail?detailView():''}`}
  function detailView(){const entry=entries.find(e=>e.id===detail);if(!entry)return'';if(!previewUrl)previewUrl=URL.createObjectURL(entry.photo);return `<section class="form-card"><div class="section-title"><h3>Factura del ${dateLabel(entry.date)}</h3><button id="invoice-close">Cerrar</button></div><img class="invoice-image" src="${previewUrl}" alt="Foto de la factura"><a class="secondary invoice-download" href="${previewUrl}" download="factura-${entry.date}.jpg">Descargar foto</a><form id="invoice-edit-date"><div class="field"><label>Corregir fecha</label><input type="date" name="date" value="${entry.date}" required></div><button class="secondary">Guardar fecha</button></form><button class="danger" id="invoice-delete">Eliminar factura</button></section>`}
  async function photoBlob(file){if(!file.type.startsWith('image/'))throw new Error('Selecciona una foto de la factura.');if(file.size>30000000)throw new Error('La foto es demasiado grande. Utiliza una imagen de menos de 30 MB.');const url=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const image=new Image;image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('No se pudo abrir la foto. Prueba con JPG o PNG.'));image.src=url});const ratio=Math.min(1,2600/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*ratio);canvas.height=Math.round(image.height*ratio);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('No se pudo preparar la foto.')),'image/jpeg',.92))}finally{URL.revokeObjectURL(url)}}
  let enginePromise;
  function engine(){return enginePromise ||=new Promise((resolve,reject)=>{if(root.Tesseract)return resolve(root.Tesseract);const script=document.createElement('script');script.src='./vendor/ocr/tesseract.min.js';script.onload=()=>resolve(root.Tesseract);script.onerror=()=>{enginePromise=null;reject(new Error('No se pudo cargar el lector. Conéctate a Internet una vez y vuelve a intentarlo.'))};document.head.appendChild(script)})}
  async function readPhoto(file){if(busy||pending)return;busy=true;error='';progress='Preparando foto…';update();let blob,worker;try{blob=await photoBlob(file);progress='Leyendo la fecha de la factura…';update();const tesseract=await engine(),base=new URL('./vendor/ocr/',location.href).href;worker=await tesseract.createWorker('spa',1,{workerPath:base+'worker.min.js',corePath:base,langPath:base,logger:m=>{if(m.status==='recognizing text'){progress=`Leyendo factura… ${Math.round(m.progress*100)} %`;const el=document.querySelector('[role="status"]');if(el&&active())el.textContent=progress}}});const {data}=await worker.recognize(blob),dates=findInvoiceDates(data.text),strong=dates.filter(d=>d.score===2),chosen=strong.length===1?strong[0]:dates.length===1&&dates[0].score>=0?dates[0]:null;if(chosen&&data.confidence>=65){await archive(blob,file.name,chosen.date);progress='';}else pending={blob,name:file.name,date:chosen?.date||dates[0]?.date||'',reason:dates.length?'Hay dudas en la lectura. Revisa la fecha antes de guardar.':'No se ha podido leer una fecha. Repite una foto más nítida o indica la fecha impresa.'}}catch(err){if(blob)pending={blob,name:file.name,date:'',reason:'No se pudo leer automáticamente. Puedes indicar la fecha o repetir la foto.'};error=err.message}finally{await worker?.terminate();busy=false;update()}}
  async function archive(photo,name,date){validateDate(date);await storage('readwrite',s=>s.add({id:crypto.randomUUID(),date,photo,name,createdAt:new Date().toISOString()}));pending=null;month=date.slice(0,7);await refresh();navigator.storage?.persist?.().catch(()=>{});error='';}
  function validateDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00').toISOString().slice(0,10)!==date)throw new Error('Revisa la fecha.');}
  function close(){detail=null;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null}
  async function action(fn){try{await fn();error=''}catch(err){error=err.name==='QuotaExceededError'?'No queda espacio en el móvil. Descarga copias y libera espacio antes de volver a intentarlo.':err.message}update()}
  function bind(isActive,render){active=isActive;redraw=render;if(!initialized){initialized=true;action(refresh)}document.querySelectorAll('#invoice-camera,#invoice-file').forEach(el=>el.onchange=()=>{const file=el.files[0];if(file)readPhoto(file)});document.querySelector('#invoice-month')?.addEventListener('change',e=>{month=e.target.value;close();update()});document.querySelectorAll('[data-invoice]').forEach(el=>el.onclick=()=>{close();detail=el.dataset.invoice;update()});document.querySelector('#invoice-close')?.addEventListener('click',()=>{close();update()});document.querySelector('#invoice-cancel')?.addEventListener('click',()=>{pending=null;error='';update()});document.querySelector('#invoice-confirm')?.addEventListener('submit',e=>{e.preventDefault();const date=new FormData(e.target).get('date');action(()=>archive(pending.blob,pending.name,date))});document.querySelector('#invoice-edit-date')?.addEventListener('submit',e=>{e.preventDefault();const date=new FormData(e.target).get('date');action(async()=>{validateDate(date);const entry={...entries.find(x=>x.id===detail),date};await storage('readwrite',s=>s.put(entry));month=date.slice(0,7);await refresh()})});document.querySelector('#invoice-delete')?.addEventListener('click',()=>{if(confirm('¿Eliminar esta factura del móvil?'))action(async()=>{await storage('readwrite',s=>s.delete(detail));close();await refresh()})})}
  root.invoiceArchive={view,bind,findInvoiceDates};
})(typeof window==='undefined'?globalThis:window);
